websocket:
  server:
    keepalive: true
    keepaliveInterval: 20000
    dropConnectionOnKeepAliveTimeout: true
    keepaliveGracePeriod: 120000
  client:
    reconnect_timeout: 1000
    connections: []

redis:
  port: 6379
  host: '127.0.0.1'

logger:
  level: 'debug' # One of: error, warn, info, verbose, debug, silly

