webserver:
  host: '127.0.0.1'
  port: 8080

websocket:
  server:
    keepalive: true
    keepaliveInterval: 20000
    dropConnectionOnKeepAliveTimeout: true
    keepaliveGracePeriod: 120000

logger:
  level: 'silly' # One of: error, warn, info, verbose, debug, silly