webserver:
  host: '0.0.0.0'
  port: 8080

websocket:
  server:
    keepalive: true
    keepaliveInterval: 20000
    dropConnectionOnKeepAliveTimeout: true
    keepaliveGracePeriod: 120000

logger:
  level: 'debug' # One of: error, warn, info, verbose, debug, silly